name: Arma

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@master

    - name: Validate SQF
      run: python3 tools/sqf_validator.py

    - name: Validate Config
      run: python3 tools/config_style_checker.py

    - name: Validate Stringtables
      run: python3 tools/stringtable_validator.py

    - name: Check for BOM
      uses: arma-actions/bom-check@master

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v2

    - name: Build addon with HEMTT
      uses: 16AAModTeam/hemtt@stable
      with:
        command: 'build --release'

    - uses: actions/upload-artifact@v2
      with:
        name: simple_suppress
        path: releases/*.zip
